version: '3.8'

services:
  web:
    image: counter-flask-web  # Use the most recent Flask app image
    expose:
      - "5002"
    depends_on:
      - redis
    networks:
      - my_network

  nginx:
    image: nginx:latest
    ports:
      - "5001:5002"  # Map port 5001 on the host to port 5002 on the container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Ensure you have your nginx.conf file in the same directory
    networks:
      - my_network

  redis:
    image: redis:alpine
    networks:
      - my_network
    volumes:
      - redis_data:/data  # Add this line to persist Redis data

networks:
  my_network:
    driver: bridge

volumes:
  redis_data:  # Define the volume at the bottom

