version: '3.8'

services:
  web:
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - redis
    networks:
      - my_network

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - my_network
    volumes: 
      - redis-data:/data  

networks:
  my_network:  

volumes:
  redis-data:  

  
